apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application
  namespace: argocd

spec:
  project: default

  sources:
  - repoURL: https://github.com/EITANPOD/devops-killer-gitOps.git
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/EITANPOD/devops-killer-project.git
    targetRevision: HEAD
    path: app-helm-chart
    helm:
      valueFiles: 
        - $values/environments/dev/values.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true