# Common values
global:
  name: devops-killer-project

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  projectRepoURL: https://github.com/EITANPOD/devops-killer-project.git
  targetRevision: HEAD

  imagePullSecrets:
    - name: regcred

# Frontend configuration
frontend:
  appname: frontend
  image:
    repository: 992382853618.dkr.ecr.us-east-1.amazonaws.com/eitan/project
    tag: frontend-83594c1
    pullPolicy: Always
  replicaCount: 3
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    hosts:
      - host: frontend.eitp.online
        paths:
          - path: /
            pathType: ImplementationSpecific
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

# Backend configuration
backend:
  appname: backend
  image:
    repository: 992382853618.dkr.ecr.us-east-1.amazonaws.com/eitan/project
    tag: backend-83594c1
    pullPolicy: Always
  replicaCount: 3
  service:
    type: ClusterIP
    port: 5000
  ingress:
    enabled: true
    hosts:
      - host: backend.eitp.online
        paths:
          - path: /
            pathType: ImplementationSpecific
  resources:
    limits:
      cpu: "1"
      memory: "1024Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"