# Common values
global:
  namespace: my-application
  imagePullSecrets:
    - name: regcred

# Frontend configuration
frontend:
  image:
    repository: 992382853618.dkr.ecr.us-east-1.amazonaws.com/eitan/project
    tag: frontend-latest
    pullPolicy: Always
  replicaCount: 2
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    hosts:
      - host: frontend.myapp.com
        paths:
          - path: /
            pathType: ImplementationSpecific
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

# Backend configuration
backend:
  image:
    repository: 992382853618.dkr.ecr.us-east-1.amazonaws.com/eitan/project
    tag: backend-latest
    pullPolicy: Always
  replicaCount: 3
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: true
    hosts:
      - host: backend.myapp.com
        paths:
          - path: /
            pathType: ImplementationSpecific
  resources:
    limits:
      cpu: "1"
      memory: "1024Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"