# Common values
global:
  name: devops-killer-project

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  projectRepoURL: https://github.com/EITANPOD/devops-killer-project.git
  targetRevision: HEAD

  imagePullSecrets:
    - name: regcred
  
# Frontend configuration
frontend:
  appname: frontend
  image:
    repository: 992382853618.dkr.ecr.us-east-1.amazonaws.com/eitan/project
    tag: frontend-b2be1f2
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    hosts:
      - host: frontend.eitp.online
        paths:
          - path: /
            pathType: ImplementationSpecific
  resources:
    limits:
      cpu: "1000m"
      memory: "512Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"

# Backend configuration
backend:
  appname: backend
  image:
    repository: 992382853618.dkr.ecr.us-east-1.amazonaws.com/eitan/project
    tag: backend-b2be1f2
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5000
  ingress:
    enabled: true
    hosts:
      - host: backend.eitp.online
        paths:
          - path: /
            pathType: ImplementationSpecific

  configmap:
    name: app-config
    env:
      FLASK_APP: "app.py"
      FLASK_ENV: "development"

  resources:
    limits:
      cpu: "1000m"
      memory: "512Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"

ingress:
  name: app-ingress
  ingressClassName: nginx
  host: app.eitp.online
  namespace: default
  pathType: ImplementationSpecific


